spring.application.name=movie-info-service
server.port=8085
management.endpoints.web.exposure.include=hystrix.stream
grpc.client.trendingService.address=static://localhost:9090
grpc.client.trendingService.negotiationType=plaintext

